
Jenkinsfile (Declarative Pipeline)

pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('build') {
            steps {
                zsh 'npm --version'
                zsh 'echo hey buddy'
            }
        }
    }
}


